# Generated by Django 4.1.13 on 2024-03-17 02:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('organisateur', 'Organisateur'), ('membre_jury', 'Membre du jury')], default='', max_length=20, verbose_name="Type d'utilisateur")),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'permissions': [('can_do_something', 'Can do something')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id_defi', models.AutoField(primary_key=True, serialize=False)),
                ('titre_defi', models.CharField(max_length=100)),
                ('piece_jointe', models.FileField(upload_to='defi_attachments/')),
                ('date_publication', models.DateField()),
                ('description', models.TextField()),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id_soumission', models.AutoField(primary_key=True, serialize=False)),
                ('fichier_soumis', models.FileField(upload_to='submission_files/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('defi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.defi')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Organisateur',
            fields=[
                ('id_organisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_organisateur', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisateur_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id_membre_jury', models.AutoField(primary_key=True, serialize=False)),
                ('nom_membre', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrilleEvaluation',
            fields=[
                ('id_grille', models.AutoField(primary_key=True, serialize=False)),
                ('critere', models.CharField(max_length=100)),
                ('note_attribuee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('defi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grille', to='app.defi')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.defi')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipe')),
                ('membre_jury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_evaluation', to='app.membrejury')),
            ],
        ),
        migrations.AddField(
            model_name='defi',
            name='organisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisateur'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niveau_d_etude', models.CharField(max_length=100)),
                ('specialite', models.CharField(choices=[('DSI', 'DSI'), ('CNM', 'CNM'), ('RSS', 'RSS')], max_length=100)),
                ('role', models.CharField(choices=[('membre', 'Membre'), ('adjoint', 'Adjoint'), ('lead', 'Lead')], default='membre_simple', max_length=20)),
                ('id_equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.equipe')),
            ],
        ),
    ]
