# Generated by Django 4.1.13 on 2024-03-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='id_equipe',
            new_name='equipe',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='role',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='role_equipe',
            field=models.CharField(choices=[('membre', 'Membre'), ('adjoint', 'Adjoint'), ('lead', 'Lead')], default='membre', max_length=20),
        ),
    ]
