# Generated by Django 4.1.13 on 2024-03-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_id_equipe_etudiant_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defi',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=20),
        ),
    ]
